### ISSUE TITLE
An internal error occurred during: "XtextReconcilerJob"

### ISSUE THREAD

**Issue by martinbaker** [martinbaker/xtextadd#1]
I sometimes get the following error when editing the DSL source code. Although the editor continues to work this needs to be sorted out. I assume the 'contentassist' parser in the ui needs to be modified in the same way as the main parser? 

!MESSAGE An internal error occurred during: "XtextReconcilerJob".
!STACK 0
java.lang.StringIndexOutOfBoundsException: String index out of range: 140
    at java.lang.String.substring(String.java:1950)
    at org.eclipse.xtext.nodemodel.impl.AbstractNode.getText(AbstractNode.java:148)
    at org.eclipse.xtext.parser.impl.PartialParsingHelper.insertChangeIntoReplaceRegion(PartialParsingHelper.java:229)
    at org.eclipse.xtext.parser.impl.PartialParsingHelper.reparse(PartialParsingHelper.java:98)
    at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.doReparse(AbstractAntlrParser.java:136)
    at org.eclipse.xtext.parser.AbstractParser.reparse(AbstractParser.java:48)
    at org.eclipse.xtext.resource.XtextResource.update(XtextResource.java:228)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.doReconcile(XtextDocumentReconcileStrategy.java:143)
    at org.eclipse.xtext.ui.editor.reconciler.XtextDocumentReconcileStrategy.reconcile(XtextDocumentReconcileStrategy.java:65)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.doRun(XtextReconciler.java:413)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.access$3(XtextReconciler.java:393)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:334)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler$1.process(XtextReconciler.java:1)
    at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:36)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.modify(XtextDocument.java:418)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.internalModify(XtextDocument.java:131)
    at org.eclipse.xtext.ui.editor.reconciler.XtextReconciler.run(XtextReconciler.java:331)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by martinbaker** [comment]
I tried modifying the 'contentassist' parser, in the UI, in the same way as the main parser. I was hoping this would fix this error but I am still getting this error. 
- I put another copy of the: PhantomToken class in the UI project .
  https://github.com/martinbaker/xtextadd/blob/master/pbase/com.euclideanspace.pbase.ui/src/com/euclideanspace/pbase/ui/PhantomToken.java
- I added another copy of the customised token source in the UI project.
  https://github.com/martinbaker/xtextadd/blob/master/pbase/com.euclideanspace.pbase.ui/src/com/euclideanspace/pbase/ui/PythonesqueTokenSource.java
- In order to use this customised TokenSource I customised the parser and in TutorialUiModule.java. 
  https://github.com/martinbaker/xtextadd/blob/master/pbase/com.euclideanspace.pbase.ui/src/com/euclideanspace/pbase/ui/TutorialUIParser.java

**Comment by martinbaker** [comment]
I have reported this bug to Xtext here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=455908

## reconciler bug

Causes the error message shown below. This happens when particular sequences of edits are done, typically involving deleting characters inside a block.

## Cause

This is because the method:
insertChangeIntoReplaceRegion(ICompositeNode rootNode, ReplaceRegion region)
in class:
org.eclipse.xtext.parser.impl.PartialParsingHelper

Sometimes gets called with the parameter 'rootNode' not set to root node but to a CompositeNode inside the root node.

## Fix

Changing the insertChangeIntoReplaceRegion method as follows fixes the problem:

```
/**
 * @author Martin Baker - fix for reconciler error.
 * This is being called with the parameter 'rootNode' not set to root node
 * I have therefore added getRootNode() call.
 */
public String insertChangeIntoReplaceRegion(ICompositeNode rootNode, ReplaceRegion region) {
  ICompositeNode reallyrootNode = rootNode.getRootNode();
  final StringBuilder builder = new StringBuilder(reallyrootNode.getText());
  region.shiftBy(0-reallyrootNode.getTotalOffset()).applyTo(builder);
  return builder.toString();
}
```

## Reproducing the fault

Only certain sequences of edits seem to cause this bug. I can reproduce it by following the procedure in this tutorial:
https://github.com/martinbaker/xtextadd/tree/master/pbase
Then inset a semicolon at the end of every line where a semicolon is valid, then delete the semicolons, in sequence, until the error message is seen.

**Comment by martinbaker** [comment]
Making sure PhantomToken is really zero length stops this happening
